### ISSUE TITLE
First code cell of Firefox demo notebook gives WebDriverException

### ISSUE THREAD

**Issue by fomightez** [ouseful-template-repos/binder-selenium-demoscraper#1]
Right now when running the first code cell after a launch, seeing `WebDriverException: Message: Service geckodriver unexpectedly exited. Status code was: 1`

Approach that seemed to work was updating/dispensing with the install you have in `postBuild` and moving the geckodriver install to where conda/mamba handles it, see [example here](https://github.com/fomightez/modelit-binder/tree/master/binder), specifically the addition of `geckodriver` to`environment.yml`.
You won't need your `postBuild` after that change since that was only running `GeckoDriverDownloader()`.

Currently the `GeckoDriverDownloader()` has an issue where it isn't getting filename correct (see below). This approach bypasses that.

fixes/bypasses these issues that crop up when you simply try to update:
- https://github.com/mozilla/geckodriver/issues/1959
- ["Error, unable to determine correct filename for 64bit linux"](https://stackoverflow.com/q/63235553/8508004)
- https://github.com/leonidessaguisagjr/webdriverdownloader/pull/12

**Comment by psychemedia** [comment]
Ah, thanks... I updated to use `geckodriver-autoinstaller` from PyPi, which seems to have fixed it...
